language: python
python: '2.7'
sudo: false

before_script:
    - pyflakes hamper
script:
    - trial hamper

notifications:
  email: false
  irc:
    channels:
    - chat.freenode.org#hamper
    on_success: always
    on_failure: always
